import json
from pydantic import BaseModel
from AWS.Lambda import LambdaEvent
from AWS.Cognito import CognitoUser
from Models import APIKey, User

AUTHORIZED_EMAIL = "purpledevilai@gmail.com"

class GenerateAPIKeyInput(BaseModel):
    org_id: str
    type: str  # "org" or "client"

def generate_api_key_handler(lambda_event: LambdaEvent, user: CognitoUser) -> APIKey.APIKey:
    """
    Generate a new API key for the specified organization.
    - Org tokens: Only purpledevilai@gmail.com, no org access check needed
    - Client tokens: Any user/org token in the org can generate
    
    POST /generate-api-key
    Body: {"org_id": "...", "type": "org|client"}
    """
    body = GenerateAPIKeyInput(**json.loads(lambda_event.body))
    
    if body.type == "org":
        # Only purpledevilai@gmail.com can create org tokens
        if user.email != AUTHORIZED_EMAIL:
            raise Exception(f"Unauthorized: Only {AUTHORIZED_EMAIL} can generate org tokens", 403)
        
        # No org membership validation - admin can create tokens for any org
        api_key = APIKey.create_org_api_key(org_id=body.org_id)
    
    elif body.type == "client":
        # Client tokens can be generated by org tokens or cognito users in the org
        # Get the user (works for both Cognito users and org API keys)
        db_user = User.get_user(user.sub)
        
        # Verify the generator has access to this org
        if body.org_id not in db_user.organizations:
            raise Exception(f"User does not have access to organization {body.org_id}", 403)
        
        # Create client token with creator's user_id
        # For org tokens: user.sub = api_key.user_id (which is the api_key_id)
        # For cognito users: user.sub = cognito user_id
        api_key = APIKey.create_client_api_key(
            org_id=body.org_id,
            user_id=user.sub  # Automatically use the creator's user_id
        )
    
    else:
        raise Exception("Invalid type. Must be 'org' or 'client'", 400)
    
    return api_key

