name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to AWS Lambda
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        if [ "${{ github.ref }}" == "refs/heads/main" ]; then
          FUNCTION_NAME="prod-ajentify-api"
        elif [ "${{ github.ref }}" == "refs/heads/staging" ]; then
          FUNCTION_NAME="staging-ajentify-api"
        else
          echo "Branch ${{ github.ref }} is not configured for deployment" >&2
          exit 1
        fi

        cd src
        zip -r9 ../lambda_function.zip .

        aws lambda update-function-code \
          --function-name $FUNCTION_NAME \
          --zip-file fileb://../lambda_function.zip
